"use client";

import { useState, useRef } from "react";
import { X, Upload, Image as ImageIcon, Loader2 } from "lucide-react";
import { uploadMultipleContentImages } from "@/services/contentImage";
import type { ContentImage } from "@/types/contentImage";

interface UploadImageModalProps {
  isOpen: boolean;
  onClose: () => void;
  onUploadSuccess?: (image: ContentImage) => void;
}

export default function UploadImageModal({
  isOpen,
  onClose,
  onUploadSuccess,
}: UploadImageModalProps) {
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [previews, setPreviews] = useState<{ file: File; preview: string }[]>(
    [],
  );
  const fileInputRef = useRef<HTMLInputElement>(null);

  const REQUIRED_WIDTH = 850;
  const REQUIRED_HEIGHT = 450;

  if (!isOpen) return null;

  const getImageDimensions = async (
    file: File,
  ): Promise<{ width: number; height: number }> => {
    // Prefer createImageBitmap when available (more reliable decoding)
    if (typeof createImageBitmap === "function") {
      const bitmap = await createImageBitmap(file);
      const dims = { width: bitmap.width, height: bitmap.height };
      bitmap.close();
      return dims;
    }

    // Fallback for older browsers
    return await new Promise((resolve, reject) => {
      const url = URL.createObjectURL(file);
      const img = new Image();
      img.onload = () => {
        URL.revokeObjectURL(url);
        resolve({ width: img.naturalWidth, height: img.naturalHeight });
      };
      img.onerror = () => {
        URL.revokeObjectURL(url);
        reject(new Error("decode_failed"));
      };
      img.src = url;
    });
  };

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0) return;

    const totalFiles = selectedFiles.length + files.length;
    if (totalFiles > 4) {
      setError(
        `You can only upload up to 4 images at a time. You currently have ${selectedFiles.length} selected.`,
      );
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
      return;
    }

    const validFiles: File[] = [];
    const validPreviews: { file: File; preview: string }[] = [];
    const errors: string[] = [];

    for (const file of files) {
      // Validate file type
      const allowedTypes = ["image/jpeg", "image/jpg", "image/png"];
      if (!allowedTypes.includes(file.type)) {
        errors.push(`${file.name}: Only JPG, PNG, and JPEG files are allowed.`);
        continue;
      }

      // Validate file size (max 2MB)
      const maxSizeBytes = 2 * 1024 * 1024;
      if (file.size > maxSizeBytes) {
        errors.push(`${file.name}: File size must be less than 2MB.`);
        continue;
      }

      // Validate dimensions (STRICT: 850×450)
      let width: number;
      let height: number;
      try {
        ({ width, height } = await getImageDimensions(file));
      } catch {
        errors.push(
          `${file.name}: Could not decode image. Please re-export it as a standard JPG or PNG.`,
        );
        continue;
      }

      if (width !== REQUIRED_WIDTH || height !== REQUIRED_HEIGHT) {
        errors.push(
          `${file.name}: Image must be ${REQUIRED_WIDTH}px × ${REQUIRED_HEIGHT}px. (Current: ${width}px × ${height}px)`,
        );
        continue;
      }

      // File is valid - create preview
      const preview = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(file);
      });

      validFiles.push(file);
      validPreviews.push({ file, preview });
    }

    if (errors.length > 0) {
      setError(errors.join("\n"));
    } else {
      setError(null);
    }

    if (validFiles.length > 0) {
      setSelectedFiles([...selectedFiles, ...validFiles]);
      setPreviews([...previews, ...validPreviews]);
    }

    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      setError("Please select at least one image file");
      return;
    }

    try {
      setUploading(true);
      setError(null);

      const response = await uploadMultipleContentImages({
        images: selectedFiles,
        // Title is auto-generated by the backend
      });

      if (response.success) {
        const uploadedImage = Array.isArray(response.data)
          ? response.data[0]
          : response.data;

        if (onUploadSuccess) {
          onUploadSuccess(uploadedImage);
        }

        resetForm();
        onClose();
      } else {
        setError(response.message || "Upload failed");
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to upload images");
    } finally {
      setUploading(false);
    }
  };

  const resetForm = () => {
    setSelectedFiles([]);
    setPreviews([]);
    setError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const removeFile = (index: number) => {
    const newFiles = selectedFiles.filter((_, i) => i !== index);
    const newPreviews = previews.filter((_, i) => i !== index);
    setSelectedFiles(newFiles);
    setPreviews(newPreviews);
    setError(null);
  };

  const handleClose = () => {
    if (!uploading) {
      resetForm();
      onClose();
    }
  };

  return (
    <>
      <div
        className="fixed inset-0 bg-black/20 backdrop-blur-sm z-[200]"
        onClick={handleClose}
      />
      <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
        <div
          className="bg-white rounded-lg shadow-xl w-full max-w-2xl"
          onClick={(e) => e.stopPropagation()}
      >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-gray-200">
            <h2 className="text-2xl font-semibold text-gray-900">
              Upload Content Image
            </h2>
            <button
              onClick={handleClose}
              disabled={uploading}
              className="cursor-pointer p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              aria-label="Close"
          >
              <X size={24} />
            </button>
          </div>

          {/* Content */}
          <div className="p-6 space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Image Files <span className="text-red-500">*</span>
                <span className="text-gray-400 text-xs ml-2">
                  (Up to 4 images)
                </span>
              </label>
              <div className="mt-1">
                {previews.length > 0 ? (
                  <div className="space-y-2">
                    <div className="grid grid-cols-2 gap-2">
                      {previews.map((item, index) => (
                        <div key={index} className="relative">
                          <div className="relative aspect-[850/450] rounded-lg border border-gray-200 overflow-hidden">
                            <img
                              src={item.preview}
                              alt={`Preview ${index + 1}`}
                              className="absolute inset-0 w-full h-full object-cover"
                            />
                            <button
                              onClick={() => removeFile(index)}
                              className="absolute top-1 right-1 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                              aria-label="Remove image"
                          >
                              <X size={14} />
                            </button>
                          </div>
                          <p className="mt-1 text-xs text-gray-600 truncate px-1">
                            {item.file.name}
                          </p>
                        </div>
                      ))}
                    </div>
                    {selectedFiles.length < 4 && (
                      <button
                        onClick={() => fileInputRef.current?.click()}
                        className="w-full border-2 border-dashed border-gray-300 rounded-lg p-4 cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-colors flex flex-col items-center justify-center"
                    >
                        <ImageIcon className="h-6 w-6 text-gray-400" />
                        <p className="mt-1 text-sm text-gray-600">
                          Add more ({selectedFiles.length}/4)
                        </p>
                      </button>
                    )}
                  </div>
                ) : (
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    className="border-2 border-dashed border-gray-300 rounded-lg p-8 cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-colors aspect-[850/450] flex flex-col items-center justify-center"
                >
                    <ImageIcon className="h-12 w-12 text-gray-400" />
                    <div className="mt-4">
                      <span className="text-blue-600 font-medium">
                        Click to upload
                      </span>
                      <span className="text-gray-500"> or drag and drop</span>
                    </div>
                    <div className="mt-2 text-xs text-gray-500 space-y-0.5 text-center">
                      <p>Note: The rule of upload content image.</p>
                      <ul className="list-disc list-outside pl-5 inline-block text-left">
                        <li>The image must be in JPG, PNG, JPEG format.</li>
                        <li>The image must be less than 2MB.</li>
                        <li>The image size must be 850px × 450px.</li>
                        <li>You can upload up to 4 images at a time.</li>
                      </ul>
                    </div>
                  </div>
                )}
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/jpeg,image/jpg,image/png"
                  onChange={handleFileSelect}
                  multiple
                  className="hidden"
                  disabled={uploading}
                />
              </div>
              {selectedFiles.length > 0 && (
                <p className="mt-2 text-sm text-gray-600">
                  Selected: {selectedFiles.length} image(s)
                </p>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-sm text-red-600 whitespace-pre-line">
                  {error}
                </p>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200">
            <button
              onClick={handleClose}
              disabled={uploading}
              className="cursor-pointer px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
              Cancel
            </button>
            <button
              onClick={handleUpload}
              disabled={selectedFiles.length === 0 || uploading}
              className="cursor-pointer flex items-center gap-2 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
          >
              {uploading ? (
                <>
                  <Loader2 size={18} className="animate-spin" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload size={18} />
                  Upload
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
