/**
 * CDN uploads use `{unixTime}_{uniqid}_{index}.ext` (see ContentCoverController / ImagesContentController).
 */
export function isAutoGeneratedStorageFilename(basename: string): boolean {
  const stem = (basename || "").replace(/\.[a-zA-Z0-9]+$/, "").trim();
  return /^\d+_[a-f0-9]+_\d+$/i.test(stem);
}

/** True when a URL basename is an opaque ID, not a human-written caption. */
export function isOpaqueImageFilename(basename: string): boolean {
  const stem = (basename || "").replace(/\.[a-zA-Z0-9]+$/, "").trim();
  if (!stem) return true;
  if (isAutoGeneratedStorageFilename(stem)) return true;
  if (/^[A-Z0-9]{12,}$/.test(stem)) return true;
  if (/^[a-f0-9]{16,}$/i.test(stem)) return true;
  return false;
}

/**
 * Labels that are not editor-written captions (original upload filenames,
 * library auto-titles, placeholder alts).
 */
export function isFilenameLikeCaption(value: string): boolean {
  const text = (value || "").trim();
  if (!text) return true;
  const lower = text.toLowerCase();
  if (lower === "inline image" || lower === "article image") return true;
  if (/\.(jpe?g|png|gif|webp|avif|bmp|svg)$/i.test(text)) return true;
  if (/^(images-content|content-cover|videos-content)-\d+$/i.test(text)) return true;
  if (isOpaqueImageFilename(text)) return true;
  return false;
}

/** Derive caption from URL filename — only when it looks human-written (legacy uploads). */
export function getImageCaptionFallback(src: string): string {
  if (!src) return "";
  try {
    const cleanPath = src.split("?")[0].split("#")[0];
    const segment = cleanPath.split("/").filter(Boolean).pop() || "";
    const decoded = decodeURIComponent(segment);
    if (isOpaqueImageFilename(decoded) || isFilenameLikeCaption(decoded)) return "";
    const withoutExt = decoded.replace(/\.[a-zA-Z0-9]+$/, "");
    return withoutExt.replace(/[-_]+/g, " ").trim();
  } catch {
    return "";
  }
}

/** Public caption: only a real editor-provided Image Name (never raw filenames). */
export function getCaptionText(
  preferred?: string | null,
  _src?: string | null,
): string {
  const text = (preferred || "").trim();
  if (!text || isFilenameLikeCaption(text)) return "";
  return text;
}

export function normalizeImageUrlKey(url: string): string {
  const raw = (url || "").trim();
  if (!raw) return "";
  try {
    const parsed = new URL(raw, "http://localhost");
    const pathname = decodeURIComponent(parsed.pathname || "");
    const basename = pathname.split("/").filter(Boolean).pop() || "";
    return basename.toLowerCase();
  } catch {
    const clean = decodeURIComponent(raw.split("?")[0].split("#")[0] || "");
    const basename = clean.split("/").filter(Boolean).pop() || clean;
    return basename.toLowerCase();
  }
}
